[application]
name = "blog"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"
[web.app]
title = "My Simple Blog"
[web.watcher]
reload_html = true
watch_path = ["src", "public"]
[web.resource]
style = ["styles.css"]
script = []
[web.resource.dev]
style = ["styles.css"]
script = []
